name: Publish DeepStack Python Documentation
on:
  push:
    branches:
      - main
jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: deepquestai/deepstack-docs-python
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS }}
        tags: "latest"
        default_branch: main
        dockerfile: Dockerfile.python
  publish-python:
    runs-on: ubuntu-latest
    steps:
      - run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        sshpass -p "{{ secrets.PYTHON_MACHINE_ACCESS }}" ssh -o StrictHostKeyChecking=no root@"{{ secrets.PYTHON_MACHINE_ADDRESS }}" "sudo docker pull deepquestai/deepstack-docs-python ; sudo docker container stop deepstack_docs && sudo docker container rm deepstack_docs ; sudo docker run -d --name deepstack_docs -p 80:5000 --restart unless-stopped deepquestai/deepstack-docs-python ; sudo docker ps ; exit"