name: Publish DeepStack Python Documentation
on: [push]
  branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: deepquestai/deepstack-docs
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS }}
        tags: "latest,v1.0.0"
        default_branch: main