name: Publish DeepStack Python Documentation to Docker
on:
  push:
    branches:
      - main
jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DIGITALOCEAN_SPACES_ZONE: ${{ secrets.DIGITALOCEAN_SPACES_ZONE }}
        DIGITALOCEAN_SPACES_SPACE: ${{ secrets.DIGITALOCEAN_SPACES_SPACE }}
        DIGITALOCEAN_SPACES_KEY: ${{ secrets.DIGITALOCEAN_SPACES_KEY }}
        DIGITALOCEAN_SPACES_KEY_SEC: ${{ secrets.DIGITALOCEAN_SPACES_KEY_SEC }}
      with:
        name: deepquestai/deepstack-docs-python
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS }}
        tags: "latest"
        default_branch: main
        dockerfile: Dockerfile.python
        buildargs: DIGITALOCEAN_SPACES_ZONE,DIGITALOCEAN_SPACES_SPACE,DIGITALOCEAN_SPACES_KEY,DIGITALOCEAN_SPACES_KEY_SEC
  publish-python:
    name: Deploy to Live Server
    needs: build-python
    runs-on: ubuntu-latest
    steps:
    - name: Deploy DeepStack Python Documentation
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PYTHON_MACHINE_ADDRESS }}
        username: root
        password: ${{ secrets.PYTHON_MACHINE_ACCESS }}
        port: 22
        script: |
          sudo docker pull deepquestai/deepstack-docs-python
          sudo docker container stop deepstack_docs && sudo docker container rm deepstack_docs
          sudo docker run -d --name deepstack_docs -p 80:5000 --restart unless-stopped deepquestai/deepstack-docs-python
          sudo docker ps
          exit